OPTIONS(SKIP=1)
LOAD DATA
INFILE '/ETAVIS/ETAVIS/fs1/EBSapps/appl/gl/12.0.0/bin/EMP_LEGACY_9767.csv'
TRUNCATE
INTO TABLE EMPLOYEE_INFO_9767
WHEN DEPARTMENT = 'AVENGERS'
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(

EMP_NAME,
HIRE_DATE "TO_DATE(:HIRE_DATE,'MM/DD/YYYY')",
DEPARTMENT ,
SALARY,
NEW_SALARY TERMINATED BY WHITESPACE  ":SALARY*2",
UPDATED_DATE "SYSDATE",
STATUS CONSTANT "LOADED"
)