CREATE OR REPLACE PROCEDURE SP_AP_SUP_SITES_DM_INT_04(
ERRBUF OUT VARCHAR2, RETCODE OUT VARCHAR2)
IS

TYPE V_RECORD IS RECORD (
ROWID VARCHAR2(240),
VENDOR_NAME VARCHAR2(240),
VENDOR_SITE_CODE VARCHAR2(15),
ORG_ID NUMBER,
SHIP_TO_LOCATION_ID NUMBER,
BILL_TO_LOCATION_ID NUMBER,
INVOICE_CURRENCY_CODE VARCHAR2(30),
PAYMENT_CURRENCY_CODE VARCHAR2(30),
START_DATE_ACTIVE DATE,
ADDRESS_LINE1 VARCHAR2(240),
CITY VARCHAR2(60),
COUNTRY VARCHAR2(60),
RECORD_STATUS VARCHAR2(30),
VERIFY_FLAG CHAR,
ERROR_MESSAGE VARCHAR2(240)
);

type rec1 is table of V_RECORD;

COL_SUPPLIER_SITE rec1:=rec1();

V_COUNT_VENDOR_NAME NUMBER;
V_VENDOR_ID NUMBER;
V_COUNT_COUNTRY NUMBER;
V_ORG_NAME VARCHAR2(20);
V_COUNT_ORG_ID NUMBER;
V_CREATED_BY VARCHAR2(100):=FND_PROFILE.VALUE('USER_ID');
 
V_LAST_UPDATE_LOGIN VARCHAR2(100):=FND_PROFILE.VALUE('LOGIN_ID');
V_LAST_UPDATED_BY VARCHAR2(100):=FND_PROFILE.VALUE('USER_ID');

BEGIN

SELECT ROWID ,
VENDOR_NAME ,
VENDOR_SITE_CODE ,
ORG_ID ,
SHIP_TO_LOCATION_ID ,
BILL_TO_LOCATION_ID ,
INVOICE_CURRENCY_CODE ,
PAYMENT_CURRENCY_CODE ,
START_DATE_ACTIVE ,
ADDRESS_LINE1 ,
CITY ,
COUNTRY ,
RECORD_STATUS ,
VERIFY_FLAG ,
ERROR_MESSAGE 
  BULK COLLECT INTO COL_SUPPLIER_SITE FROM XX_SUPPLIER_TEMP_03 WHERE ERROR_MESSAGE IS NULL;

FOR V_INDEX IN COL_SUPPLIER_SITE.FIRST.. COL_SUPPLIER_SITE.LAST
  LOOP
  
    --VALIDATION FOR VENDOR_ID
    
    BEGIN
    
    SELECT COUNT(VENDOR_NAME) INTO V_COUNT_VENDOR_NAME FROM PO_VENDORS WHERE UPPER(VENDOR_NAME)=UPPER(COL_SUPPLIER_SITE(V_INDEX).VENDOR_NAME);
    
    IF V_COUNT_VENDOR_NAME>0 THEN
      SELECT VENDOR_ID INTO V_VENDOR_ID FROM PO_VENDORS WHERE UPPER(VENDOR_NAME)=UPPER(COL_SUPPLIER_SITE(V_INDEX).VENDOR_NAME);
    
    ELSE
      UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='INVALID VENDOR NAME' 
      WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
    
    END IF;
    
    END;
    
    --VALIDATION FOR VENDOR_SITE_CODE
    
    BEGIN
    
    IF COL_SUPPLIER_SITE(V_INDEX).VENDOR_SITE_CODE IS NULL THEN
      UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='Vendor site code cannot be null' 
      WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
    
    END IF;
    
    END;
    
    --VALIDATION FOR COUNTRY
    
    BEGIN
    
    SELECT COUNT(TERRITORY_CODE) INTO V_COUNT_COUNTRY FROM FND_TERRITORIES WHERE TERRITORY_CODE=COL_SUPPLIER_SITE(V_INDEX).COUNTRY;
    
    IF V_COUNT_COUNTRY<=0 THEN
      UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='Invalid country' 
      WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
    
    END IF;
    
    END;
    
    --VALIDATION FOR ORG_ID
    
    BEGIN
    
    IF COL_SUPPLIER_SITE(V_INDEX).ORG_ID IS NULL THEN
      UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='Org_id cannot be null' 
      WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
      
    ELSE
    
      SELECT COUNT(ORGANIZATION_ID) INTO V_COUNT_ORG_ID FROM ORG_ORGANIZATION_DEFINITIONS
      WHERE ORGANIZATION_ID=COL_SUPPLIER_SITE(V_INDEX).ORG_ID;
      IF V_COUNT_ORG_ID<=0 THEN
        UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='Invalid Organization' 
        WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
        COMMIT;
        CONTINUE;
        
      ELSE
        SELECT ORGANIZATION_NAME INTO V_ORG_NAME FROM ORG_ORGANIZATION_DEFINITIONS 
        WHERE ORGANIZATION_ID=COL_SUPPLIER_SITE(V_INDEX).ORG_ID;
        IF V_ORG_NAME!='Vision Operations' THEN
          UPDATE XX_SUPPLIER_TEMP_03 SET VERIFY_FLAG='N', ERROR_MESSAGE='Invalid Organization' 
          WHERE ROWID=COL_SUPPLIER_SITE(V_INDEX).ROWID;
          COMMIT;
          CONTINUE;
        END IF;
      
      END IF;
    
    END IF; 
    
    END;
    
    --INSERTION IN INTERFACE TABLE AP_SUPPLIER_SITES_INT_03_DUMMY
    
    IF COL_SUPPLIER_SITE(V_INDEX).ERROR_MESSAGE IS NULL THEN
      INSERT INTO AP_SUP_SITES_INT_DMY_G04(VENDOR_SITE_INTERFACE_ID, VENDOR_ID, VENDOR_SITE_CODE, ORG_ID, SHIP_TO_LOCATION_ID, BILL_TO_LOCATION_ID, 
                                                  INVOICE_CURRENCY_CODE, PAYMENT_CURRENCY_CODE, ADDRESS_LINE1, CITY, COUNTRY, 
                                                   CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY)
                                                    VALUES(SEQ_VENDOR_SITE_IFACE_ID_03.NEXTVAL, V_VENDOR_ID,
                                                    COL_SUPPLIER_SITE(V_INDEX).VENDOR_SITE_CODE, COL_SUPPLIER_SITE(V_INDEX).ORG_ID,
                                                    COL_SUPPLIER_SITE(V_INDEX).SHIP_TO_LOCATION_ID, COL_SUPPLIER_SITE(V_INDEX).BILL_TO_LOCATION_ID, 
                                                    COL_SUPPLIER_SITE(V_INDEX).INVOICE_CURRENCY_CODE, COL_SUPPLIER_SITE(V_INDEX).PAYMENT_CURRENCY_CODE,
                                                     COL_SUPPLIER_SITE(V_INDEX).ADDRESS_LINE1, 
                                                    COL_SUPPLIER_SITE(V_INDEX).CITY,COL_SUPPLIER_SITE(V_INDEX).COUNTRY,
                                                    
                                                     V_CREATED_BY, SYSDATE, SYSDATE, V_LAST_UPDATE_LOGIN, 
                                                    V_LAST_UPDATED_BY);
          
    COMMIT;
    END IF;                                              
  
  END LOOP;

END;