CREATE OR REPLACE PROCEDURE SP_AP_SUP_SITES_INT_04(ERRBUF OUT VARCHAR2, RETCODE OUT VARCHAR2) 
IS
  TYPE TYPE_REC_SUP_SITES_INFO IS RECORD(ROWID VARCHAR2(200),
  VENDOR_NAME VARCHAR2(240),
  VENDOR_SITE_CODE VARCHAR2(15),
  ORG_ID NUMBER,
  SHIP_TO_LOCATION_ID NUMBER,
  BILL_TO_LOCATION_ID NUMBER,
  INVOICE_CURRENCY_CODE VARCHAR2(30),
  PAYMENT_CURRENCY_CODE VARCHAR2(30),
  START_DATE_ACTIVE DATE,
  ADDRESS_LINE1 VARCHAR2(240),
  CITY VARCHAR2(60),
  COUNTRY VARCHAR2(60),
  RECORD_STATUS VARCHAR2(30),
  VERIFY_FLAG CHAR,
  ERROR_MESSAGE VARCHAR2(240));
  TYPE TYPE_SUPPLIER_SITES_INFO IS TABLE OF TYPE_REC_SUP_SITES_INFO;
  COL_SUPPLIER_SITES_INFO TYPE_SUPPLIER_SITES_INFO := TYPE_SUPPLIER_SITES_INFO();
  V_COUNT_VENDOR NUMBER;
  V_COUNT_COUNTRY NUMBER;
  V_COUNT_ORG NUMBER;
  V_VENDOR_ID NUMBER;
  V_ORGANIZATION_NAME VARCHAR2(100);
BEGIN
  SELECT ROWID,
  VENDOR_NAME ,
  VENDOR_SITE_CODE ,
  ORG_ID ,
  SHIP_TO_LOCATION_ID ,
  BILL_TO_LOCATION_ID ,
  INVOICE_CURRENCY_CODE ,
  PAYMENT_CURRENCY_CODE ,
  START_DATE_ACTIVE ,
  ADDRESS_LINE1 ,
  CITY ,
  COUNTRY ,
  RECORD_STATUS ,
  VERIFY_FLAG ,
  ERROR_MESSAGE  BULK COLLECT INTO COL_SUPPLIER_SITES_INFO FROM XX_SUPPLIER_TEMP_04 WHERE ERROR_MESSAGE IS NULL;

  FOR V_INDEX IN COL_SUPPLIER_SITES_INFO.FIRST..COL_SUPPLIER_SITES_INFO.LAST
  LOOP
  ---------VALIDATION OF VENDOR_NAME FOR VENDOR_ID------------------------
    BEGIN
      SELECT COUNT(VENDOR_NAME) INTO V_COUNT_VENDOR FROM PO_VENDORS WHERE 
      UPPER(VENDOR_NAME) = UPPER(COL_SUPPLIER_SITES_INFO(V_INDEX).VENDOR_NAME);
        IF V_COUNT_VENDOR<=0 THEN 
          UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='INVALID VENDOR NAME' WHERE
          ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
          COMMIT;
          CONTINUE;
          ELSE
          SELECT VENDOR_ID INTO V_VENDOR_ID FROM PO_VENDORS WHERE 
          UPPER(VENDOR_NAME) = UPPER(COL_SUPPLIER_SITES_INFO(V_INDEX).VENDOR_NAME);
        END IF;
    END;
  -----------------------VALIDATION OF VENDOR_SITE_CODE------------------
  BEGIN
    IF COL_SUPPLIER_SITES_INFO(V_INDEX).VENDOR_SITE_CODE IS NULL THEN
      UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='Vendor site code cannot be null' WHERE
      ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
    END IF;
  END;
  -------------------VALIDATION OF COUNTRY-------------------------
  BEGIN
    SELECT COUNT(TERRITORY_CODE) INTO V_COUNT_COUNTRY FROM FND_TERRITORIES WHERE 
    TERRITORY_CODE = COL_SUPPLIER_SITES_INFO(V_INDEX).COUNTRY;
    IF V_COUNT_COUNTRY <=0 THEN
      UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='Invalid country' WHERE
      ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
    END IF;
  END;
  
  -------------------VALIDATION OF ORG_ID--------------------------
  BEGIN
    IF COL_SUPPLIER_SITES_INFO(V_INDEX).ORG_ID IS NULL THEN
      UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='Org_id cannot be null' WHERE
      ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
      COMMIT;
      CONTINUE;
      ELSE
      SELECT COUNT(ORGANIZATION_NAME) INTO V_COUNT_ORG FROM ORG_ORGANIZATION_DEFINITIONS WHERE
      ORGANIZATION_ID = COL_SUPPLIER_SITES_INFO(V_INDEX).ORG_ID;
      IF V_COUNT_ORG <=0 THEN
        UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='Invalid organization' WHERE
        ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
        COMMIT;
        CONTINUE;
        ELSE
        SELECT ORGANIZATION_NAME INTO V_ORGANIZATION_NAME FROM ORG_ORGANIZATION_DEFINITIONS WHERE 
        ORGANIZATION_ID = COL_SUPPLIER_SITES_INFO(V_INDEX).ORG_ID;
      IF V_ORGANIZATION_NAME != 'Vision Operations' THEN
          UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='N',ERROR_MESSAGE='Invalid organization' WHERE
          ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
          COMMIT;
          CONTINUE;
          END IF;
        END IF;
    END IF;
  END;
  -----------------INSERT INTO AP_SUPPLIER_SITES_INT_DMY_G04 TABLE---------------------
  ---DROP SEQUENCE SEQ_VENDOR_SITE_INT_ID_G04--------------------------
  ---CREATE SEQUENCE SEQ_VENDOR_SITE_INT_ID_G04 START WITH 767103--------------------
  DECLARE
  V_CREATED_BY VARCHAR2(100) := FND_PROFILE.VALUE('USER_ID');
  V_LAST_UPDATE_LOGIN VARCHAR2(100) := FND_PROFILE.VALUE('LOGIN_ID');
  V_LAST_UPDATED_BY VARCHAR2(100):= FND_PROFILE.VALUE('USER_ID');
  BEGIN
    IF COL_SUPPLIER_SITES_INFO(V_INDEX).ERROR_MESSAGE IS NULL THEN
      UPDATE XX_SUPPLIER_TEMP_04 SET VERIFY_FLAG='Y',ERROR_MESSAGE='NO ERROR',RECORD_STATUS='SUCCESS' WHERE
      ROWID = COL_SUPPLIER_SITES_INFO(V_INDEX).ROWID;
      INSERT INTO AP_SUP_SITES_INT_DMY_G04(VENDOR_SITE_INTERFACE_ID,VENDOR_SITE_CODE,VENDOR_ID,ORG_ID,CREATED_BY,CREATION_DATE,
      LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,LAST_UPDATED_BY,SHIP_TO_LOCATION_ID,BILL_TO_LOCATION_ID,INVOICE_CURRENCY_CODE,PAYMENT_CURRENCY_CODE,ADDRESS_LINE1,
      CITY,COUNTRY) VALUES(SEQ_VENDOR_SITE_INT_ID_G04.NEXTVAL,
      COL_SUPPLIER_SITES_INFO(V_INDEX).VENDOR_SITE_CODE,
      V_VENDOR_ID,COL_SUPPLIER_SITES_INFO(V_INDEX).ORG_ID,V_CREATED_BY,
      SYSDATE,SYSDATE,V_LAST_UPDATE_LOGIN,V_LAST_UPDATED_BY,
      COL_SUPPLIER_SITES_INFO(V_INDEX).SHIP_TO_LOCATION_ID,
      COL_SUPPLIER_SITES_INFO(V_INDEX).BILL_TO_LOCATION_ID,
      COL_SUPPLIER_SITES_INFO(V_INDEX).INVOICE_CURRENCY_CODE,
      COL_SUPPLIER_SITES_INFO(V_INDEX).PAYMENT_CURRENCY_CODE,
      COL_SUPPLIER_SITES_INFO(V_INDEX).ADDRESS_LINE1,
      COL_SUPPLIER_SITES_INFO(V_INDEX).CITY,
      COL_SUPPLIER_SITES_INFO(V_INDEX).COUNTRY
      );
    COMMIT;
    END IF;
  END;
  END LOOP;
EXCEPTION
WHEN OTHERS THEN
   FND_FILE.PUT_LINE(FND_FILE.LOG,'SOMETHING WENT WRONG');
  END;
  ------------------------------PROCEDURE END-------------------------------------